name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  CARGO_INCREMENTAL: 0

jobs:
  rust:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          profile: minimal
          override: true
          components: rustfmt, clippy, llvm-tools-preview
    - name: Cargo install
      run: cargo install cargo-binutils
    - name: Run cargo fmt
      run: cargo fmt -- --check
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features
    - name: Run cargo build
      run: cargo build
    - name: Run cargo test
      run: cargo test
    - name: Run cargo clean
      run: cargo clean
    - name: Run cargo test
      env:
        RUSTFLAGS: '-Z instrument-coverage'
      run: cargo test
    - name: cargo profdata
      run: cargo profdata -- merge -sparse default.profraw -o default.profdata
    - name: coverage
      run: cargo cov -- show --use-color --ignore-filename-regex='/.cargo/registry' --instr-profile=default.profdata --object target/debug/deps/ical_rrule-b2a70cd2ca5a8a21 --show-instantiations --show-line-counts-or-regions --Xdemangler=rustfilt
    - name: coverage summary
      run: cargo cov -- report --use-color --ignore-filename-regex='/.cargo/registry' --instr-profile=default.profdata --object target/debug/deps/ical_rrule-b2a70cd2ca5a8a21