name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  CARGO_INCREMENTAL: 0

jobs:
  rust:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          profile: minimal
          override: true
          components: rustfmt, clippy
    - name: Run cargo fmt
      run: cargo fmt -- --check
    - name: Run cargo build
      run: cargo build
    - name: Run cargo clippy
      run: cargo clippy
    - name: Run cargo test
      run: cargo test
