# inspired by https://github.com/rust-analyzer/rust-analyzer/blob/master/.github/workflows/ci.yaml
name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  CARGO_INCREMENTAL: 0

jobs:
  rust:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          profile: minimal
          override: true
          components: rustfmt, clippy
    - name: Run cargo fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt -- --check
    - name: Run cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build
    - name: Run cargo clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
    - name: Run cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test